# Tasks to perform


1.   Prepare the dataset to be fed to Fully Connected Neural Network. With preparation, I mean convert all the categorial and string values to number representation acceptable for the neural network
2.   Define a fully connected deep neural network with three hidden layers of 128, 64 and 32 with appropriate input and output layers. Remember column with title 'y' is output variable
3.   Split the data in 70-30 for train and test
4.   Train the model on all 20 input variables and report the test accuracy
5.   Use PCA to extract first five principle components on this dataset and report test accuracy on these principle components 
6.   How much variance is covered by these five components? Please discuss it inside a text cell
7.   Repeat experiment 5 and 6, this time rather selecting five components, select as many as components are required to achieve minimum 70% test accuracy
8.    How many components are required to achieve 70% performance?   

# Necessary Imports

In [1]:
# Data manipulation
import pandas as pd # for data manipulation

# Visualization
import plotly.express as px # for data visualization

# Skleran
from sklearn.preprocessing import StandardScaler # for data standardization
from sklearn.metrics import classification_report # for model evaluation metrics
from sklearn.preprocessing import OrdinalEncoder # to encode categorical variables
from sklearn.preprocessing import LabelEncoder # to encode categorical variables

# Mounting Google Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Dataset Path on Drive

In [28]:
dataset_path = '/content/drive/MyDrive/Colab Notebooks/datasets/banking/banking.csv'

# Reading Dataset CSV

In [29]:
# Read in data
df = pd.read_csv(dataset_path, encoding='utf-8')
# Print dataframe
df

age          job  marital            education  default housing loan  \
0       44  blue-collar  married             basic.4y  unknown     yes   no   
1       53   technician  married              unknown       no      no   no   
2       28   management   single    university.degree       no     yes   no   
3       39     services  married          high.school       no      no   no   
4       55      retired  married             basic.4y       no     yes   no   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   59      retired  married          high.school  unknown      no  yes   
41184   31    housemaid  married             basic.4y  unknown      no   no   
41185   42       admin.   single    university.degree  unknown     yes  yes   
41186   48   technician  married  professional.course       no      no  yes   
41187   25      student   single          high.school       no      no   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0       cellular   aug         thu  ...         1    999         0   
1       cellular   nov         fri  ...         1    999         0   
2       cellular   jun         thu  ...         3      6         2   
3       cellular   apr         fri  ...         2    999         0   
4       cellular   aug         fri  ...         1      3         1   
...          ...   ...         ...  ...       ...    ...       ...   
41183  telephone   jun         thu  ...         1    999         0   
41184  telephone   may         thu  ...         2    999         0   
41185  telephone   may         wed  ...         3    999         0   
41186  telephone   oct         tue  ...         2    999         0   
41187  telephone   may         fri  ...         4    999         0   

          poutcome emp_var_rate  cons_price_idx  cons_conf_idx  euribor3m  \
0      nonexistent          1.4          93.444          -36.1      4.963   
1      nonexistent         -0.1          93.200          -42.0      4.021   
2          success         -1.7          94.055          -39.8      0.729   
3      nonexistent         -1.8          93.075          -47.1      1.405   
4          success         -2.9          92.201          -31.4      0.869   
...            ...          ...             ...            ...        ...   
41183  nonexistent          1.4          94.465          -41.8      4.866   
41184  nonexistent          1.1          93.994          -36.4      4.860   
41185  nonexistent          1.1          93.994          -36.4      4.857   
41186  nonexistent         -3.4          92.431          -26.9      0.742   
41187  nonexistent          1.1          93.994          -36.4      4.859   

       nr_employed  y  
0           5228.1  0  
1           5195.8  0  
2           4991.6  1  
3           5099.1  0  
4           5076.2  1  
...            ... ..  
41183       5228.1  0  
41184       5191.0  0  
41185       5191.0  0  
41186       5017.5  0  
41187       5191.0  0  

[41188 rows x 21 columns]

In [30]:
len(list(df.columns))

21

In [31]:
df.shape

(41188, 21)

In [32]:
print(df.columns)

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp_var_rate', 'cons_price_idx',
       'cons_conf_idx', 'euribor3m', 'nr_employed', 'y'],
      dtype='object')


In [33]:
df['duration'].dtypes

dtype('int64')

# Task 1. Converting categorial and string values to number representation acceptable for the neural network

In [34]:
y = df['y']
df.drop("y", axis=1, inplace=True)

In [35]:
df1 = df.select_dtypes(exclude=["number"])
df2 = df.select_dtypes(include=["number"])

In [36]:
df1

job  marital            education  default housing loan  \
0      blue-collar  married             basic.4y  unknown     yes   no   
1       technician  married              unknown       no      no   no   
2       management   single    university.degree       no     yes   no   
3         services  married          high.school       no      no   no   
4          retired  married             basic.4y       no     yes   no   
...            ...      ...                  ...      ...     ...  ...   
41183      retired  married          high.school  unknown      no  yes   
41184    housemaid  married             basic.4y  unknown      no   no   
41185       admin.   single    university.degree  unknown     yes  yes   
41186   technician  married  professional.course       no      no  yes   
41187      student   single          high.school       no      no   no   

         contact month day_of_week     poutcome  
0       cellular   aug         thu  nonexistent  
1       cellular   nov         fri  nonexistent  
2       cellular   jun         thu      success  
3       cellular   apr         fri  nonexistent  
4       cellular   aug         fri      success  
...          ...   ...         ...          ...  
41183  telephone   jun         thu  nonexistent  
41184  telephone   may         thu  nonexistent  
41185  telephone   may         wed  nonexistent  
41186  telephone   oct         tue  nonexistent  
41187  telephone   may         fri  nonexistent  

[41188 rows x 10 columns]

In [37]:
df2

age  duration  campaign  pdays  previous  emp_var_rate  cons_price_idx  \
0       44       210         1    999         0           1.4          93.444   
1       53       138         1    999         0          -0.1          93.200   
2       28       339         3      6         2          -1.7          94.055   
3       39       185         2    999         0          -1.8          93.075   
4       55       137         1      3         1          -2.9          92.201   
...    ...       ...       ...    ...       ...           ...             ...   
41183   59       222         1    999         0           1.4          94.465   
41184   31       196         2    999         0           1.1          93.994   
41185   42        62         3    999         0           1.1          93.994   
41186   48       200         2    999         0          -3.4          92.431   
41187   25       112         4    999         0           1.1          93.994   

       cons_conf_idx  euribor3m  nr_employed  
0              -36.1      4.963       5228.1  
1              -42.0      4.021       5195.8  
2              -39.8      0.729       4991.6  
3              -47.1      1.405       5099.1  
4              -31.4      0.869       5076.2  
...              ...        ...          ...  
41183          -41.8      4.866       5228.1  
41184          -36.4      4.860       5191.0  
41185          -36.4      4.857       5191.0  
41186          -26.9      0.742       5017.5  
41187          -36.4      4.859       5191.0  

[41188 rows x 10 columns]

In [38]:
from sklearn.preprocessing import LabelEncoder 
oe = LabelEncoder()

for column in df1:
  col = oe.fit_transform(df1[column])
  df1.drop(column, axis=1, inplace=True)
  df1[column] = col

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [39]:
df= pd.concat([df1,df2],axis=1)

In [40]:
print(df['housing'].unique())
print(df['loan'].unique())
print(df['marital'].unique())

[2 0 1]
[0 2 1]
[1 2 0 3]


# After Conversion, DataFrame is

In [41]:
print(len(list(df.columns)))
print(df.shape)
print(df.columns)

20
(41188, 20)
Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'age', 'duration', 'campaign',
       'pdays', 'previous', 'emp_var_rate', 'cons_price_idx', 'cons_conf_idx',
       'euribor3m', 'nr_employed'],
      dtype='object')


In [42]:
import numpy as np
X = df

In [43]:
print(X.columns)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'age', 'duration', 'campaign',
       'pdays', 'previous', 'emp_var_rate', 'cons_price_idx', 'cons_conf_idx',
       'euribor3m', 'nr_employed'],
      dtype='object')


In [44]:
len(list(X.columns))

20

# Task 2.   Define a fully connected deep neural network with three hidden layers of 128, 64 and 32 with appropriate input and output layers.

In [45]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([                        
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(32, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

In [46]:
model.compile(optimizer="rmsprop",
              loss="binary_crossentropy",
              metrics=["accuracy"])

# Task 3.   Split the data in 70-30 for train and test

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y)

In [48]:
print('Labels count in y:', np.bincount(y))
print('Labels count in y_train:', np.bincount(y_train))
print('Labels count in y_test:', np.bincount(y_test))

Labels count in y: [36548  4640]
Labels count in y_train: [25583  3248]
Labels count in y_test: [10965  1392]


Scaling the values between -1 and 1 using standard Scalar

In [49]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
X = sc.transform(X)

In [50]:
X_train_std

array([[-0.7646362 , -0.28082372, -0.82101149, ...,  0.88250628,
         0.71162804,  0.3331707 ],
       [-1.04237834, -1.92643929,  1.05306968, ..., -0.47893703,
         0.77325139,  0.84601854],
       [-1.04237834,  1.36479185,  1.05306968, ..., -0.32766555,
         0.26298705,  0.39952298],
       ...,
       [-0.20915194, -0.28082372, -0.3524912 , ..., -1.23529442,
        -1.31618318, -0.93719904],
       [-0.7646362 , -1.92643929, -1.28953178, ..., -0.28444513,
         0.77325139,  0.84601854],
       [ 1.45730087, -0.28082372,  0.58454939, ...,  0.88250628,
         0.71681132,  0.3331707 ]])

Splitting training set into Train and Validation

In [51]:
X_train_std, x_val, y_train, y_val = train_test_split(X_train_std, y_train, test_size=0.15, shuffle=True)

# Task 4. Train the model on all 20 input variables and report the test accuracy

In [52]:
history = model.fit(X_train_std,
                    y_train,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_val, y_val))

Epoch 1/20
48/48 [==============================] - 4s 7ms/step - loss: 0.2767 - accuracy: 0.8908 - val_loss: 0.2085 - val_accuracy: 0.9103
Epoch 2/20
48/48 [==============================] - 0s 4ms/step - loss: 0.1984 - accuracy: 0.9110 - val_loss: 0.2006 - val_accuracy: 0.9114
Epoch 3/20
48/48 [==============================] - 0s 4ms/step - loss: 0.1917 - accuracy: 0.9123 - val_loss: 0.1986 - val_accuracy: 0.9121
Epoch 4/20
48/48 [==============================] - 0s 4ms/step - loss: 0.1881 - accuracy: 0.9138 - val_loss: 0.1969 - val_accuracy: 0.9098
Epoch 5/20
48/48 [==============================] - 0s 6ms/step - loss: 0.1850 - accuracy: 0.9159 - val_loss: 0.1966 - val_accuracy: 0.9101
Epoch 6/20
48/48 [==============================] - 0s 7ms/step - loss: 0.1822 - accuracy: 0.9165 - val_loss: 0.1967 - val_accuracy: 0.9114
Epoch 7/20
48/48 [==============================] - 0s 7ms/step - loss: 0.1798 - accuracy: 0.9177 - val_loss: 0.1952 - val_accuracy: 0.9091
Epoch 8/20
48/48 [==

In [53]:
results = model.evaluate(X_test, y_test)

387/387 [==============================] - 1s 2ms/step - loss: 952.9459 - accuracy: 0.8874


# Test Accuracy is 88%

# Task 5. Use PCA to extract first five principle components on this dataset and report test accuracy on these principle components 

In [54]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
X_pca = pca.fit_transform(X)
X_pca.shape

(41188, 5)

In [55]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.3, shuffle=True)

In [56]:
X_train_pca1, x_val, y_train, y_val = train_test_split(X_train_pca, y_train, test_size=0.15, shuffle=True)

In [57]:
from tensorflow import keras
from tensorflow.keras import layers
pca_model = keras.Sequential([                        
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(32, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])
pca_model.compile(optimizer="rmsprop",
              loss="binary_crossentropy",
              metrics=["accuracy"])

In [58]:
history = pca_model.fit(X_train_pca1,
                    y_train,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_val, y_val))

Epoch 1/20
48/48 [==============================] - 1s 7ms/step - loss: 0.3528 - accuracy: 0.8725 - val_loss: 0.2750 - val_accuracy: 0.8992
Epoch 2/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2676 - accuracy: 0.8978 - val_loss: 0.2548 - val_accuracy: 0.8997
Epoch 3/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2524 - accuracy: 0.8990 - val_loss: 0.2466 - val_accuracy: 0.9008
Epoch 4/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2456 - accuracy: 0.9002 - val_loss: 0.2394 - val_accuracy: 0.9001
Epoch 5/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2409 - accuracy: 0.9007 - val_loss: 0.2412 - val_accuracy: 0.9020
Epoch 6/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2386 - accuracy: 0.9015 - val_loss: 0.2346 - val_accuracy: 0.9020
Epoch 7/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2364 - accuracy: 0.9024 - val_loss: 0.2373 - val_accuracy: 0.9022
Epoch 8/20
48/48 [==

In [59]:
results = pca_model.evaluate(X_test_pca, y_test)

387/387 [==============================] - 1s 2ms/step - loss: 0.2258 - accuracy: 0.9008


# Test Accuracy is around 89%

# Task 6. How much variance is covered by these five components?

In [60]:
pca.explained_variance_ratio_

array([0.21351343, 0.08352298, 0.07713646, 0.06797864, 0.05700536])

In [61]:
sum(pca.explained_variance_ratio_)

0.4991568732290207

# 49% Variance is covered by first 5 components

# Task 7. Now, Select as many as components are required to achieve minimum 70% test accuracy

In [62]:
from sklearn.decomposition import PCA
pca1 = PCA(0.70)
X_pca1 = pca1.fit_transform(X)
X_pca1.shape

(41188, 9)

In [63]:
X_train_pca1, X_test_pca1, y_train1, y_test1 = train_test_split(X_pca1, y, test_size=0.3, random_state=30 , shuffle=True)

In [64]:
X_train_pca2, x_val1, y_train1, y_val1 = train_test_split(X_train_pca1, y_train1, test_size=0.15, shuffle=True)

In [65]:
X_train_pca2.shape

(24506, 9)

In [66]:
model1 = keras.Sequential([                 
    layers.Dense(64, activation="relu"),
    layers.Dense(32, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])
model1.compile(optimizer="rmsprop",
              loss="binary_crossentropy",
              metrics=["accuracy"])

In [67]:
history = model1.fit(X_train_pca2,
                    y_train1,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_val1, y_val1))

Epoch 1/20
48/48 [==============================] - 1s 6ms/step - loss: 0.3905 - accuracy: 0.8668 - val_loss: 0.2620 - val_accuracy: 0.9064
Epoch 2/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2415 - accuracy: 0.9026 - val_loss: 0.2137 - val_accuracy: 0.9128
Epoch 3/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2190 - accuracy: 0.9055 - val_loss: 0.2061 - val_accuracy: 0.9128
Epoch 4/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2125 - accuracy: 0.9069 - val_loss: 0.1994 - val_accuracy: 0.9138
Epoch 5/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2088 - accuracy: 0.9087 - val_loss: 0.1970 - val_accuracy: 0.9145
Epoch 6/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2063 - accuracy: 0.9100 - val_loss: 0.1953 - val_accuracy: 0.9158
Epoch 7/20
48/48 [==============================] - 0s 4ms/step - loss: 0.2045 - accuracy: 0.9104 - val_loss: 0.1960 - val_accuracy: 0.9149
Epoch 8/20
48/48 [==

In [68]:
results = model1.evaluate(X_test_pca1, y_test1)

387/387 [==============================] - 1s 2ms/step - loss: 0.2072 - accuracy: 0.9069


# Test Accuracy is around 90%

In [69]:
pca1.explained_variance_ratio_

array([0.21351343, 0.08352558, 0.07713652, 0.06799623, 0.05700569,
       0.05435776, 0.05192398, 0.05037521, 0.0495195 ])

In [70]:
sum(pca1.explained_variance_ratio_)

0.7053539063704914

# 70% Variance is covered by these 9 components

# 9 components are required to give 70% Accuracy 